### ISSUE TITLE
app close due to NoSuchMethodError: No virtual method setSkuId (Ljava/lang/String;)V in class Lcom/mapbox/android/telemetry/AppUserTurnstile

### ISSUE THREAD

**Issue by ajay29592** [mapbox/mapbox-gl-native-android#633]
I download demo from github and try to build in my android studio 4.1.1, build version 30, gradle version 6.5.1-all with following dependencies:
`com.mapbox.mapboxsdk:mapbox-core:4.3.0`
`com.mapbox.mapboxsdk:mapbox-services:4.3.0`
`com.mapbox.mapboxsdk:mapbox-geojson:4.3.0`
`com.mapbox.mapboxsdk:mapbox-android-telemetry:4.3.0`
`com.mapbox.mapboxsdk:mapbox-android-gestures:0.4.0`

I refer ReadMe file and also include `MapboxGLAndroidSDK.aar` dependency. now i build my project successfully but when I rum it, it is crashed with following error:
`NoSuchMethodError: NoVirtual Method setSkuId(Ljava/lang/string;)V in class Lcom/mapbox/android/telemetry/AppUserTurnstile; or it super class`
what should I need to do to resolve this error?
